language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
services:
  - mysql
install:
  - composer install
  - mv config/config.test.php config/config.php
before_script:
  - mysql -e 'create database traq_test;'
script: php tests/test.php
